# Generated by Django 4.1.6 on 2023-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='book')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='author')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('avilble', 'avilble'), ('rental', 'rental'), ('sold', 'sold')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_period', models.IntegerField(blank=True, null=True)),
                ('catgory', models.ForeignKey(on_delete=property, to='liprary.catgory')),
            ],
        ),
    ]
